export type Language = 'en' | 'sw' | 'kl' | 'lh' | 'lu';

export const languages: Record<Language, string> = {
  en: 'English',
  sw: 'Kiswahili',
  kl: 'Kalenjin',
  lh: 'Luhya',
  lu: 'Dholuo',
};

type TranslationKeys =
  | 'appName' | 'home' | 'symptoms' | 'emergency' | 'chat' | 'facilities'
  | 'analytics' | 'booking' | 'settings' | 'welcomeTitle' | 'welcomeSubtitle'
  | 'checkSymptoms' | 'emergencyHelp' | 'findFacility' | 'talkToAI'
  | 'enterSymptom' | 'send' | 'analyzing' | 'urgencyEmergency' | 'urgencyHigh'
  | 'urgencyNormal' | 'bookAppointment' | 'selectFacility' | 'selectDate'
  | 'confirm' | 'language' | 'nearestFacilities' | 'liveAnalytics'
  | 'callEmergency' | 'typeMessage';

const translations: Record<Language, Record<TranslationKeys, string>> = {
  en: {
    appName: 'AFYAROOT',
    home: 'Home',
    symptoms: 'Symptoms',
    emergency: 'Emergency',
    chat: 'Chat AI',
    facilities: 'Facilities',
    analytics: 'Analytics',
    booking: 'Booking',
    settings: 'Settings',
    welcomeTitle: 'Your AI Health Assistant',
    welcomeSubtitle: 'Get instant health guidance, find facilities, and access emergency help — even offline.',
    checkSymptoms: 'Check Symptoms',
    emergencyHelp: 'Emergency Help',
    findFacility: 'Find Facility',
    talkToAI: 'Talk to AI',
    enterSymptom: 'Describe your symptoms...',
    send: 'Send',
    analyzing: 'Analyzing symptoms...',
    urgencyEmergency: 'Emergency',
    urgencyHigh: 'High Priority',
    urgencyNormal: 'Normal',
    bookAppointment: 'Book Appointment',
    selectFacility: 'Select Facility',
    selectDate: 'Select Date',
    confirm: 'Confirm',
    language: 'Language',
    nearestFacilities: 'Nearest Facilities',
    liveAnalytics: 'Live Health Analytics',
    callEmergency: 'Call Emergency',
    typeMessage: 'Type a message...',
  },
  sw: {
    appName: 'AFYAROOT',
    home: 'Nyumbani',
    symptoms: 'Dalili',
    emergency: 'Dharura',
    chat: 'Ongea AI',
    facilities: 'Vituo',
    analytics: 'Takwimu',
    booking: 'Uhifadhi',
    settings: 'Mipangilio',
    welcomeTitle: 'Msaidizi wako wa Afya wa AI',
    welcomeSubtitle: 'Pata ushauri wa afya papo hapo, tafuta vituo, na upate msaada wa dharura — hata bila mtandao.',
    checkSymptoms: 'Angalia Dalili',
    emergencyHelp: 'Msaada wa Dharura',
    findFacility: 'Tafuta Kituo',
    talkToAI: 'Ongea na AI',
    enterSymptom: 'Elezea dalili zako...',
    send: 'Tuma',
    analyzing: 'Inachambua dalili...',
    urgencyEmergency: 'Dharura',
    urgencyHigh: 'Kipaumbele Kikubwa',
    urgencyNormal: 'Kawaida',
    bookAppointment: 'Hifadhi Miadi',
    selectFacility: 'Chagua Kituo',
    selectDate: 'Chagua Tarehe',
    confirm: 'Thibitisha',
    language: 'Lugha',
    nearestFacilities: 'Vituo vya Karibu',
    liveAnalytics: 'Takwimu za Moja kwa Moja',
    callEmergency: 'Piga Simu ya Dharura',
    typeMessage: 'Andika ujumbe...',
  },
  kl: {
    appName: 'AFYAROOT',
    home: 'Kaa',
    symptoms: 'Dalili',
    emergency: 'Saa ne',
    chat: 'Ng\'alalek AI',
    facilities: 'Bik ab sayet',
    analytics: 'Takwimu',
    booking: 'Booking',
    settings: 'Ng\'alechut',
    welcomeTitle: 'AI ne konech ko',
    welcomeSubtitle: 'Nyone konetisyet ak konech ko, chok bik ab sayet, ak konech ko saa ne.',
    checkSymptoms: 'Check Dalili',
    emergencyHelp: 'Konech Saa Ne',
    findFacility: 'Chok Kituo',
    talkToAI: 'Ng\'alal ak AI',
    enterSymptom: 'Soman dalili...',
    send: 'Iach',
    analyzing: 'Inachambua...',
    urgencyEmergency: 'Saa Ne',
    urgencyHigh: 'Muhimu',
    urgencyNormal: 'Kawaida',
    bookAppointment: 'Book Miadi',
    selectFacility: 'Til Kituo',
    selectDate: 'Til Tarehe',
    confirm: 'Imach',
    language: 'Ng\'olyot',
    nearestFacilities: 'Bik ab Sayet ne Thiik',
    liveAnalytics: 'Takwimu',
    callEmergency: 'Kuur Saa Ne',
    typeMessage: 'Som ujumbe...',
  },
  lh: {
    appName: 'AFYAROOT',
    home: 'Mulyango',
    symptoms: 'Ebimanyi',
    emergency: 'Obuhasi',
    chat: 'Khushiyana AI',
    facilities: 'Ebitsio',
    analytics: 'Ebibalilo',
    booking: 'Okhutesha',
    settings: 'Emitsemba',
    welcomeTitle: 'Omufasanyi we Obulamu bwa AI',
    welcomeSubtitle: 'Fumila obulagirizi bwe obulamu, khola ebitsio, ne obufasanyi bwe obuhasi.',
    checkSymptoms: 'Lola Ebimanyi',
    emergencyHelp: 'Obufasanyi bwe Obuhasi',
    findFacility: 'Khola Ekitsio',
    talkToAI: 'Shiyana ne AI',
    enterSymptom: 'Manyi ebimanyi byosi...',
    send: 'Linda',
    analyzing: 'Inachambua...',
    urgencyEmergency: 'Obuhasi',
    urgencyHigh: 'Muhimu',
    urgencyNormal: 'Kawaida',
    bookAppointment: 'Tesha Miadi',
    selectFacility: 'Sala Ekitsio',
    selectDate: 'Sala Itariki',
    confirm: 'Imila',
    language: 'Olulimi',
    nearestFacilities: 'Ebitsio ebi Handu',
    liveAnalytics: 'Ebibalilo',
    callEmergency: 'Khukha Obuhasi',
    typeMessage: 'Andika ujumbe...',
  },
  lu: {
    appName: 'AFYAROOT',
    home: 'Dala',
    symptoms: 'Ranyisi',
    emergency: 'Kinde',
    chat: 'Wuo gi AI',
    facilities: 'Kar thieth',
    analytics: 'Nonro',
    booking: 'Chano',
    settings: 'Loso',
    welcomeTitle: 'Jakony mar Ngima mar AI',
    welcomeSubtitle: 'Yud kony mar ngima piyo, yud kar thieth, kendo yud kony mar kinde — kata ka ionge e mtandao.',
    checkSymptoms: 'Non Ranyisi',
    emergencyHelp: 'Kony mar Kinde',
    findFacility: 'Yud Kar Thieth',
    talkToAI: 'Wuo gi AI',
    enterSymptom: 'Ler ranyisi magi...',
    send: 'Or',
    analyzing: 'Pod nono ranyisi...',
    urgencyEmergency: 'Kinde',
    urgencyHigh: 'Maduong',
    urgencyNormal: 'Kawaida',
    bookAppointment: 'Chan Romo',
    selectFacility: 'Yier Kar Thieth',
    selectDate: 'Yier Tarik',
    confirm: 'Sir',
    language: 'Dhok',
    nearestFacilities: 'Kar Thieth Machiegni',
    liveAnalytics: 'Nonro mar Ngima',
    callEmergency: 'Luong Kinde',
    typeMessage: 'Ndik ote...',
  },
};

export function t(key: TranslationKeys, lang: Language = 'en'): string {
  return translations[lang]?.[key] || translations.en[key] || key;
}
